### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by rudovjan** [kennethjiang/js-file-download#24] opened 2017-09-12 16:58 UTC
Unfortunately this plugin does not work with safari. Any plan to take a look on that?

**Comment by kennethjiang** [comment] 2017-09-23 17:09
Sorry for the delay. I've been tied up recently.

This is a known issue. Look at issue #5. It seems there is a fork to address Safari https://github.com/rmiller-fc/react-file-download/commit/12c4312bb17683b434575b09ea68708a51c448eb. I can't merge that fix though as it breaks the current behavior of opening up download in a new tab.

Of course if you have better solution feel free to send in a PR.

**Comment by rudovjan** [comment] 2017-09-26 16:17
Thank you! 

Strange thing happened :) So I copy&paste your code into project, change it into ES6, let it compile with babel and code started working. 

1. If i left it as a es5 dependency it does not work
2. compiled to es5 using babel, started to work

Once will have little bit more time,  I have a plan to take a look on that.

**Comment by kennethjiang** [comment] 2017-09-27 14:19
Great. It'll be awesome if you can help add transpiler to this project (using rollup or similar tool) so that everyone can benefit from your work!

**Comment by exihuatl** [comment] 2019-12-09 17:12
I've created a simple PR with a fix/workaround: #55

**Comment by kennethjiang** [comment] 2019-12-10 01:16
Sorry just saw your comment. Can you give a bit more details on how your PR fixes this issue? Thanks lot @exihuatl

**Comment by exihuatl** [comment] 2019-12-10 11:35
@kennethjiang The problem is that we are removing blob in the same cycle as opening a new window. This causes some problems for iOS Safari which shows an enigmatic error message.

Some resources:
https://discussions.apple.com/thread/250191294
https://github.com/mozilla/pdf.js/issues/8152
https://bugs.webkit.org/show_bug.cgi?id=190351

**Comment by Vovan-VE** [comment] 2020-03-04 08:21
The problem still exists on Safari/13.3.1. Sometimes it works, sometimes it's not. Behavior is unstable. Look's like `0` timeout is not enough.

**Comment by motevets** [comment] 2020-08-19 15:51
I believe that #63 fixes this issue (which has been released in 0.4.12). If this issue still persists, please feel free to open a new issue.

**Closed by motevets** 2020-08-19 15:51 UTC
